[versions]
compose = "1.5.4"
androidx-appcompat = "1.6.1"
androidx-lifecycle = "2.6.2"
ktor = "2.3.5"
coroutine = "1.7.3"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
kotlin-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
android-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
ktorClient-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClient-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorClient-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

[plugins]